using Serilog.Context;

namespace EnterpriseInventory.Api.Http;

/// <summary>
/// Gives every request a correlation ID: returned in the <c>X-Correlation-ID</c> header and in error responses,
/// attached to every log entry and, later, to audit records. The ID is always generated by the server; a value
/// sent by the client is ignored so it cannot be used to forge or mix up log entries.
/// </summary>
internal sealed class CorrelationIdMiddleware(RequestDelegate next)
{
    public const string HeaderName = "X-Correlation-ID";
    public const string LogPropertyName = "CorrelationId";

    public async Task InvokeAsync(HttpContext context)
    {
        var correlationId = Guid.NewGuid().ToString("N");
        context.TraceIdentifier = correlationId;

        // Set when the response starts: the exception handler clears headers set earlier.
        context.Response.OnStarting(() =>
        {
            context.Response.Headers[HeaderName] = correlationId;
            return Task.CompletedTask;
        });

        using (LogContext.PushProperty(LogPropertyName, correlationId))
        {
            await next(context);
        }
    }
}
